### ISSUE TITLE
join team form

### ISSUE THREAD

**Issue by wahidustoz** [ilmhub-uz/akiss#4]
/team page da team haqida info bor. 

Eng tagiga team'ga qo'shilish uchun forma yaratiladi. 
- [x] Fullname
- [x] Phone
- [x] Email
- [x] Subject (fan nomi, max 100 string)
- [x] ExperienceInYears (positive number)
- [x] EnglishLevel [C2, C1, B2, B1, A2, A1, A0] enum
- [x] Resume (optional) [.pdf, .docx] single file (max 3 MB)

Yuqoridagi fayllar ma'lumotlar GoogleSheets va file GoogleDrive'da Resumes degan papkaga post bo'ladi. 

> Good Luck :)

**Comment by wahid-d** [comment]
- Sitatli: darsingiz sifatini oshiring va o'quvchilaringiz natijalarini yaxshilang
- Qiziqarli: dars jarayoniga qiziqarli elementlar qo'shing va o'quvchilarni jalb eting 
- Masofaviy: Masofaviy ta'lim uchun video kontentlar yarating va auditoriyangizni kengaytiring
- Ustama: Malakangizni oshiring va maoshingizga 35~100% qo'shing

**Comment by wahid-d** [comment]
ustozlar
Ishga qabul qilmamiz 

Agar sizda quyidagi ko'nikma va tajribalar bo'lsa, bizning jamoaga qo'shilib kariyerangizni zamonvayiv maktabda mo'may daromad asosida quring.

**Comment by wahid-d** [comment]
Barcha fanlardan ustozlarni tanlov asosida ishga taklif etamiz
Ingliz tilida dars bera oladigan ustozlar tanlovlarsiz barcha fanlarga qabul qilinadi
Tajriba va ko'nikmalaridan kelib chiqib ustozlarni qoniqtiradigan  maosh kelishiladi

**Comment by wahid-d** [comment]
![image](https://user-images.githubusercontent.com/30383473/156770595-a4039156-f28a-43e8-a70f-2c7133add853.jpeg)

**Comment by wahid-d** [comment]
![image](https://user-images.githubusercontent.com/30383473/156777879-957af3d1-945f-4cc1-ab68-8df6f1105d79.jpeg)
