### ISSUE TITLE
confirm forms

### ISSUE THREAD

**Issue by Furqat-DevDo** [ilmhub-uz/akiss#51]
-  after submitting clean input fields values .
-  notification should to be bigger
- submit button must be disabled after submitting.
- do that for each form in the website

**Comment by wahid-d** [comment]
@Furqat-DevDo Chyotki issue ochibsiz. Qoyil.

@ilmhub-uz/ilmhub-team o'rganinglar!


@Furqat-DevDo Har bir bullet point uchun allohida issue ochib hammaga assign qilib qo'yaman.

**Comment by Furqat-DevDo** [comment]
ok rahmat

**Comment by Furqat-DevDo** [comment]
bu issue tugagan
